# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f5a7546d11c5661c02b4b60c8ff214b2842d854f77f8f53f4fcfa827a493e14cf427959fc36e6cc58482017a353cd5930b873f5cfdd65ea65e86fc299fe01c

test:
  secret_key_base: a29af488cad1b57ad370c30777c59159790ac28c0cb90cb13722e4ca0c10e2eacb0f80a8b4abbbc6d5ec16f07718735bb7bb5604fcf2b236c0f38f4916223600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
